apiVersion: apps/v1
kind: Deployment
metadata:
  name: auction-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: auction-service
  template:
    metadata:
      labels:
        app: auction-service
    spec:
      containers:
        - name: auction-service
          image: auction-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
