apiVersion: apps/v1
kind: Deployment
metadata:
  name: bidding-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bidding-service
  template:
    metadata:
      labels:
        app: bidding-service
    spec:
      containers:
        - name: bidding-service
          image: biddingapi:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5001
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Development"
            - name: ASPNETCORE_URLS
              value: "http://+:5001"
            - name: ConnectionStrings__Database
              value: "Server=biddb;Database=BidDb;User Id=sa;Password=SwN12345678;Encrypt=False;TrustServerCertificate=True"
            - name: MessageBroker__Host
              value: "amqp://messagebroker:5672"
            - name: MessageBroker__UserName
              value: "guest"
            - name: MessageBroker__Password
              value: "guest"