apiVersion: v1
kind: Service
metadata:
  name: bidding-service
spec:
  selector:
    app: bidding-service
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30080
  type: NodePort
