apiVersion: apps/v1
kind: Deployment
metadata:
  name: bidding-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bidding-service
  template:
    metadata:
      labels:
        app: bidding-service
    spec:
      containers:
        - name: bidding-service
          image: biddingapi:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5001
          env:
            - name: ASPNETCORE_URLS
              value: "http://+:5001"  # Ensure ASP.NET listens on 5001
