apiVersion: v1
kind: Service
metadata:
  name: bidding-service
spec:
  selector:
    app: bidding-service
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
      nodePort: 30080
  type: NodePort
