apiVersion: apps/v1
kind: Deployment
metadata:
  name: bidding-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bidding-service
  template:
    metadata:
      labels:
        app: bidding-service
    spec:
      containers:
        - name: bidding-service
          image: bidding-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
