apiVersion: v1
kind: Service
metadata:
  name: messagebroker
spec:
  ports:
    - name: amqp
      port: 5672             # RabbitMQ default port
      targetPort: 5672
    - name: management
      port: 15672            # RabbitMQ management port (optional)
      targetPort: 15672
  selector:
    app: messagebroker
