version: '3.4'

services:
  auctiondb:
    image: postgres

  auction.api:
    image: ${DOCKER_REGISTRY-}auctionapi
    build:
      context: .
      dockerfile: Services/Auction/Auction.API/Dockerfile

volumes:
  postgres_auction:    

