version: '3.4'

services:
  auctiondb:
    image: postgres
    networks:
      - swiped_network
    volumes:
      - postgres_auction:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=AuctionDb
    ports:
      - "5432:5432"

<<<<<<< Updated upstream
=======
  distributedcache:
    image: redis
    networks:
      - swiped_network
    ports:
      - "6379:6379"

>>>>>>> Stashed changes
  biddb:
    image: mcr.microsoft.com/mssql/server
    networks:
      - swiped_network
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=SwN12345678
    ports:
      - "1433:1433"

<<<<<<< Updated upstream
=======
  jobschedulerdb:
    image: mcr.microsoft.com/mssql/server
    networks:
      - swiped_network
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=SwN12345678
    ports:
      - "1434:1433"

  messagebroker:
    image: rabbitmq:management
    networks:
      - swiped_network
    hostname: bidding-mq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"

  contractdb:
    image: postgres
    networks:
      - swiped_network
    volumes:
      - postgres_contract:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ContractDb
    ports:
      - "5433:5432"

>>>>>>> Stashed changes
  auction.api:
    image: ${DOCKER_REGISTRY-}auctionapi
    build:
      context: .
      dockerfile: Services/Auction/Auction.API/Dockerfile
<<<<<<< Updated upstream
=======
    networks:
      - swiped_network
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Database=Server=auctiondb;Port=5432;Database=AuctionDb;User Id=postgres;Password=postgres;Include Error Detail=true
      - ConnectionStrings__Redis=distributedcache:6379
      - MessageBroker__Host=amqp://bidding-mq:5672
      - MessageBroker__UserName=guest
      - MessageBroker__Password=guest
    depends_on:
      - auctiondb
      - messagebroker
      - distributedcache
    ports:
      - "6000:8080"
      - "6060:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
>>>>>>> Stashed changes

  bidding.api:
    image: ${DOCKER_REGISTRY-}biddingapi
    build:
      context: .
      dockerfile: Services/Bidding/Bidding.API/Dockerfile
<<<<<<< Updated upstream

volumes:
  postgres_auction:    


=======
    networks:
      - swiped_network
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Database=Server=biddb;Database=BidDb;User Id=sa;Password=SwN12345678;Encrypt=False;TrustServerCertificate=True
      - MessageBroker__Host=amqp://bidding-mq:5672
      - MessageBroker__UserName=guest
      - MessageBroker__Password=guest
    depends_on:
      - biddb
      - messagebroker
    ports:
      - "6001:8080"
      - "6061:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  jobscheduler.api:
    image: ${DOCKER_REGISTRY-}jobschedulerapi
    build:
      context: .
      dockerfile: Services/JobScheduler/JobScheduler.API/Dockerfile
    networks:
      - swiped_network
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Database=Server=jobschedulerdb;Database=JobSchedulerDb;User Id=sa;Password=SwN12345678;Encrypt=False;TrustServerCertificate=True
      - MessageBroker__Host=amqp://bidding-mq:5672
      - MessageBroker__UserName=guest
      - MessageBroker__Password=guest
    depends_on:
      - jobschedulerdb
      - messagebroker
    ports:
      - "6004:8080"
      - "6064:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  ml-service:
    build:
      context: ./Services/MLService
      dockerfile: Dockerfile
    container_name: ml_service
    ports:
      - "5002:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=host.docker.internal;Port=3307;Database=MachineLearningDB;User=User1;Password=User123;
      - MessageBroker__Host=amqp://src-messagebroker-1:5672
      - MessageBroker__UserName=guest
      - MessageBroker__Password=guest
    depends_on:
      - messagebroker
    volumes:
      - ./Services/MLService/ML/Models:/app/ML/Models
    networks:
      - swiped_network

  biddingresult.api:
    image: ${DOCKER_REGISTRY-}biddingresultapi
    build:
      context: .
      dockerfile: Services/BiddingResult/BiddingResult.API/Dockerfile
    networks:
      - swiped_network
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Database=Server=contractdb;Port=5432;Database=ContractDb;User Id=postgres;Password=postgres;Include Error Detail=true
      - MessageBroker__Host=amqp://bidding-mq:5672
      - MessageBroker__UserName=guest
      - MessageBroker__Password=guest
    depends_on:
      - contractdb
      - messagebroker
    ports:
      - "6003:8080"
      - "6063:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

networks:
  swiped_network:
    driver: bridge

volumes:
  postgres_auction:
  postgres_contract:
>>>>>>> Stashed changes
